// Login
export const AUTHENTICATION_LOGIN_ATTEMPT: string = "AUTHENTICATION_LOGIN_ATTEMPT"
export const AUTHENTICATION_LOGIN_FAILURE: string = "AUTHENTICATION_LOGIN_FAILURE"
export const AUTHENTICATION_LOGIN_SUCCESS: string = "AUTHENTICATION_LOGIN_SUCCESS"

// Logout
export const AUTHENTICATION_LOGOUT_FAILURE: string = "AUTHENTICATION_LOGOUT_FAILURE"
export const AUTHENTICATION_LOGOUT_SUCCESS: string = "AUTHENTICATION_LOGOUT_SUCCESS"

// Session
export const AUTHENTICATION_SESSION_CHECK_ATTEMPT: string = "AUTHENTICATION_SESSION_CHECK_ATTEMPT"
export const AUTHENTICATION_SESSION_CHECK_FAILURE: string = "AUTHENTICATION_SESSION_CHECK_FAILURE"
export const AUTHENTICATION_SESSION_CHECK_SUCCESS: string = "AUTHENTICATION_SESSION_CHECK_SUCCESS"


// Podcast
export const PODCAST_SET_PODCASTS: string = "PODCAST_SET_PODCASTS"
export const PODCAST_ADD_PODCAST: string = "PODCAST_ADD_PODCASTS"
export const PODCAST_UPDATE_PODCASTS_ATTEMPT: string = "PODCAST_UPDATE_PODCASTS_ATTEMPT"